In [39]:
import pandas as pd
import numpy as np

# A messy customer dataset
messy_data = {
    "customer_id": [1, 2, 3, 4, 5, 6, 7, 8],
    "name": ["Rohit", "Amit", "Neha", "Vikram", None, "Priya", "Suresh", None],
    "age": [28, 35, np.nan, 45, 30, np.nan, 52, 41],
    "city": ["Delhi", "Mumbai", "Bangalore", None, "Chennai", "Delhi", None, "Mumbai"],
    "purchase_amount": [50000, 75000, np.nan, 45000, 60000, 80000, np.nan, 55000],
    "last_purchase_date": ["2024-01-15", "2024-02-20", None, "2024-03-10", "2024-02-05", None, "2024-01-30", "2024-03-25"]
}

df = pd.DataFrame(messy_data)
print(df)

   customer_id    name   age       city  purchase_amount last_purchase_date
0            1   Rohit  28.0      Delhi          50000.0         2024-01-15
1            2    Amit  35.0     Mumbai          75000.0         2024-02-20
2            3    Neha   NaN  Bangalore              NaN               None
3            4  Vikram  45.0       None          45000.0         2024-03-10
4            5    None  30.0    Chennai          60000.0         2024-02-05
5            6   Priya   NaN      Delhi          80000.0               None
6            7  Suresh  52.0       None              NaN         2024-01-30
7            8    None  41.0     Mumbai          55000.0         2024-03-25

In [2]:
# True/False mask of missing cells across the whole DataFrame
df.isna()

   customer_id   name    age   city  purchase_amount  last_purchase_date
0        False  False  False  False            False               False
1        False  False  False  False            False               False
2        False  False   True  False             True                True
3        False  False  False   True            False               False
4        False   True  False  False            False               False
5        False  False   True  False            False                True
6        False  False  False   True             True               False
7        False   True  False  False            False               False

In [3]:
# Per-column count of missing values
df.isna().sum()

customer_id           0
name                  2
age                   2
city                  2
purchase_amount       2
last_purchase_date    2
dtype: int64

In [4]:
# Total missing cells in the whole DataFrame
df.isna().sum().sum()

np.int64(10)

In [5]:
# Percentage missing per column
(df.isna().sum()/ len(df)) * 100

customer_id            0.0
name                  25.0
age                   25.0
city                  25.0
purchase_amount       25.0
last_purchase_date    25.0
dtype: float64

In [6]:
# Rows that have ANY missing values
df[df.isna().any(axis = 1)]

   customer_id    name   age       city  purchase_amount last_purchase_date
2            3    Neha   NaN  Bangalore              NaN               None
3            4  Vikram  45.0       None          45000.0         2024-03-10
4            5    None  30.0    Chennai          60000.0         2024-02-05
5            6   Priya   NaN      Delhi          80000.0               None
6            7  Suresh  52.0       None              NaN         2024-01-30
7            8    None  41.0     Mumbai          55000.0         2024-03-25

In [7]:
# Rows that have ALL values missing (complete junk rows)
df[df.isna().all(axis = 1)]

Empty DataFrame
Columns: [customer_id, name, age, city, purchase_amount, last_purchase_date]
Index: []

In [8]:
# Columns that have ANY missing values
df.columns[df.isna().any()]

Index(['name', 'age', 'city', 'purchase_amount', 'last_purchase_date'], dtype='object')

In [11]:
# Opposite — completely clean rows
df[df.notna().all(axis = 1)]

   customer_id   name   age    city  purchase_amount last_purchase_date
0            1  Rohit  28.0   Delhi          50000.0         2024-01-15
1            2   Amit  35.0  Mumbai          75000.0         2024-02-20

In [12]:
df.isna().sum()              # axis=0 default — sum down rows = count per column

customer_id           0
name                  2
age                   2
city                  2
purchase_amount       2
last_purchase_date    2
dtype: int64

In [13]:
df.isna().sum(axis=1)        # sum across columns = count per row

0    0
1    0
2    3
3    1
4    1
5    2
6    2
7    1
dtype: int64

In [14]:
# Q1: How many missing values per column?
df.isna().sum()

customer_id           0
name                  2
age                   2
city                  2
purchase_amount       2
last_purchase_date    2
dtype: int64

In [15]:
# Q2: How many missing values total in the DataFrame?
df.isna().sum().sum()

np.int64(10)

In [18]:
# Q3: Percentage missing per column
(df.isna().sum()/ len(df) ) *100

customer_id            0.0
name                  25.0
age                   25.0
city                  25.0
purchase_amount       25.0
last_purchase_date    25.0
dtype: float64

In [21]:
# Q4: Show only rows that have at least one missing value
df[df.isna().any(axis = 1)]

   customer_id    name   age       city  purchase_amount last_purchase_date
2            3    Neha   NaN  Bangalore              NaN               None
3            4  Vikram  45.0       None          45000.0         2024-03-10
4            5    None  30.0    Chennai          60000.0         2024-02-05
5            6   Priya   NaN      Delhi          80000.0               None
6            7  Suresh  52.0       None              NaN         2024-01-30
7            8    None  41.0     Mumbai          55000.0         2024-03-25

In [22]:
# Q5: Show only rows where ALL values are present
df[df.notna().all(axis = 1)]

   customer_id   name   age    city  purchase_amount last_purchase_date
0            1  Rohit  28.0   Delhi          50000.0         2024-01-15
1            2   Amit  35.0  Mumbai          75000.0         2024-02-20

In [23]:
# Q6: How many missing values in each row?
df.isna().sum(axis=1)

0    0
1    0
2    3
3    1
4    1
5    2
6    2
7    1
dtype: int64

In [24]:
# Total rows
print(f"Total rows: {len(df)}")

# Rows with any missing value
missing_rows = df.isna().any(axis=1).sum()
print(f"Rows with any missing: {missing_rows}")

# Percentage that would be lost with dropna()
pct_lost = (missing_rows / len(df)) * 100
print(f"Percentage lost if we dropna(): {pct_lost}%")

Total rows: 8
Rows with any missing: 6
Percentage lost if we dropna(): 75.0%

In [25]:
# Just to see what dropna does mechanically
print("Original rows:", len(df))
print("After dropna():", len(df.dropna()))
print("After dropna(subset=['age']):", len(df.dropna(subset=["age"])))
print("After dropna(subset=['age', 'city']):", len(df.dropna(subset=["age", "city"])))
print("After dropna(thresh=5):", len(df.dropna(thresh=5)))

Original rows: 8
After dropna(): 2
After dropna(subset=['age']): 6
After dropna(subset=['age', 'city']): 4
After dropna(thresh=5): 5

In [26]:
# Strategy 1: constant
print("--- Fill city with 'Unknown' ---")
print(df["city"].fillna("Unknown"))

--- Fill city with 'Unknown' ---
0        Delhi
1       Mumbai
2    Bangalore
3      Unknown
4      Chennai
5        Delhi
6      Unknown
7       Mumbai
Name: city, dtype: object

In [27]:
# Strategy 2: zero (let's see if this is appropriate or not)
print("\n--- Fill purchase_amount with 0 ---")
print(df["purchase_amount"].fillna(0))

--- Fill purchase_amount with 0 ---
0    50000.0
1    75000.0
2        0.0
3    45000.0
4    60000.0
5    80000.0
6        0.0
7    55000.0
Name: purchase_amount, dtype: float64

In [31]:
# Strategy 3: mean
print("\n--- Fill age with mean ---")
print(df["age"].fillna(df["age"].mean()))

--- Fill age with mean ---
0    28.0
1    35.0
2    38.5
3    45.0
4    30.0
5    38.5
6    52.0
7    41.0
Name: age, dtype: float64

In [32]:
# Strategy 3b: median
print("\n--- Fill age with median ---")
print(df["age"].fillna(df["age"].median()))

--- Fill age with median ---
0    28.0
1    35.0
2    38.0
3    45.0
4    30.0
5    38.0
6    52.0
7    41.0
Name: age, dtype: float64

In [34]:
# Strategy 4: mode (most common)
print("\n--- Fill city with mode ---")
print(df["city"].fillna(df["city"].mode()[0]))

--- Fill city with mode ---
0        Delhi
1       Mumbai
2    Bangalore
3        Delhi
4      Chennai
5        Delhi
6        Delhi
7       Mumbai
Name: city, dtype: object

In [35]:
df["age"].fillna(df["age"].mean())   # returns new Series, df unchanged

0    28.0
1    35.0
2    38.5
3    45.0
4    30.0
5    38.5
6    52.0
7    41.0
Name: age, dtype: float64

In [36]:
#save the change, assign it back:
#df["age"] = df["age"].fillna(df["age"].mean())

In [37]:
df.fillna({
    "name": "Unknown",
    "age": df["age"].median(),
    "city": "Unknown",
    "purchase_amount": 0,
    "last_purchase_date": "Not Recorded"
})

   customer_id     name   age       city  purchase_amount last_purchase_date
0            1    Rohit  28.0      Delhi          50000.0         2024-01-15
1            2     Amit  35.0     Mumbai          75000.0         2024-02-20
2            3     Neha  38.0  Bangalore              0.0       Not Recorded
3            4   Vikram  45.0    Unknown          45000.0         2024-03-10
4            5  Unknown  30.0    Chennai          60000.0         2024-02-05
5            6    Priya  38.0      Delhi          80000.0       Not Recorded
6            7   Suresh  52.0    Unknown              0.0         2024-01-30
7            8  Unknown  41.0     Mumbai          55000.0         2024-03-25

In [38]:
# Apply your decisions
df_filled = df.fillna({
    "name": "Unknown",
    "age": df["age"].median(),
    "city": "Unknown",                      # since we don't know analysis context, default to Unknown
    "purchase_amount": 0,
    "last_purchase_date": "Not Recorded"
})

print(df_filled)
print(f"\nMissing values after fillna: {df_filled.isna().sum().sum()}")

   customer_id     name   age       city  purchase_amount last_purchase_date
0            1    Rohit  28.0      Delhi          50000.0         2024-01-15
1            2     Amit  35.0     Mumbai          75000.0         2024-02-20
2            3     Neha  38.0  Bangalore              0.0       Not Recorded
3            4   Vikram  45.0    Unknown          45000.0         2024-03-10
4            5  Unknown  30.0    Chennai          60000.0         2024-02-05
5            6    Priya  38.0      Delhi          80000.0       Not Recorded
6            7   Suresh  52.0    Unknown              0.0         2024-01-30
7            8  Unknown  41.0     Mumbai          55000.0         2024-03-25

Missing values after fillna: 0