In [1]:
import pandas as pd

sales_csv = """sale_id,salesperson,amount,sale_date
1,Rohit,50000,2024-01-15
2,Amit,75000,2024-02-20
3,Rohit,60000,2024-02-25
4,Neha,80000,2024-03-10
5,Amit,45000,2024-04-05
6,Neha,90000,2024-05-22
7,Rohit,55000,2024-06-18
8,Neha,70000,2024-07-30
9,Amit,85000,2024-09-12
10,Rohit,65000,2024-11-08"""

with open("dated_sales.csv", "w") as f:
    f.write(sales_csv)

df = pd.read_csv("dated_sales.csv")
print(df)
print("\nColumn types:")
print(df.dtypes)

   sale_id salesperson  amount   sale_date
0        1       Rohit   50000  2024-01-15
1        2        Amit   75000  2024-02-20
2        3       Rohit   60000  2024-02-25
3        4        Neha   80000  2024-03-10
4        5        Amit   45000  2024-04-05
5        6        Neha   90000  2024-05-22
6        7       Rohit   55000  2024-06-18
7        8        Neha   70000  2024-07-30
8        9        Amit   85000  2024-09-12
9       10       Rohit   65000  2024-11-08

Column types:
sale_id         int64
salesperson    object
amount          int64
sale_date      object
dtype: object

In [2]:
# Try to find the latest sale
print(df["sale_date"].max())

2024-11-08

In [3]:
# Try to find sales from after March 1
#df[df["sale_date"] > "2024-03-01"]    # this works (alphabetical luck)

# Try date arithmetic
#df["sale_date"] - df["sale_date"].min()    # ERROR — can't subtract strings

In [4]:
df["sale_date"] = pd.to_datetime(df["sale_date"])
print(df.dtypes)

sale_id                 int64
salesperson            object
amount                  int64
sale_date      datetime64[ns]
dtype: object

In [5]:
print(df["sale_date"].max())
print(df["sale_date"].min())
print(df["sale_date"].max()-df["sale_date"].min())

2024-11-08 00:00:00
2024-01-15 00:00:00
298 days 00:00:00

In [6]:
# US format MM/DD/YYYY
pd.to_datetime("01/15/2024", format="%m/%d/%Y")

Timestamp('2024-01-15 00:00:00')

In [7]:
# Indian format DD/MM/YYYY  
pd.to_datetime("15/01/2024", format="%d/%m/%Y")

Timestamp('2024-01-15 00:00:00')

In [8]:
# Verbose format
pd.to_datetime("15-Jan-2024", format="%d-%b-%Y")

Timestamp('2024-01-15 00:00:00')

In [9]:
# Default ISO format (works without specifying)
pd.to_datetime("2024-01-15")

Timestamp('2024-01-15 00:00:00')

In [10]:
# Bad data
mixed_dates = pd.Series(["2024-01-15", "2024-02-20", "not a date", "2024-04-05"])

#pd.to_datetime(mixed_dates)            # ERROR
pd.to_datetime(mixed_dates, errors="coerce")   # converts bad rows to NaT

0   2024-01-15
1   2024-02-20
2          NaT
3   2024-04-05
dtype: datetime64[ns]

In [11]:
# Q1: Convert the column properly (you've done this — confirm it works)
df["sale_date"] = pd.to_datetime(df["sale_date"])
print(df.dtypes)

sale_id                 int64
salesperson            object
amount                  int64
sale_date      datetime64[ns]
dtype: object

In [12]:
# Q2: Now you can sort properly by date
print(df.sort_values("sale_date"))

   sale_id salesperson  amount  sale_date
0        1       Rohit   50000 2024-01-15
1        2        Amit   75000 2024-02-20
2        3       Rohit   60000 2024-02-25
3        4        Neha   80000 2024-03-10
4        5        Amit   45000 2024-04-05
5        6        Neha   90000 2024-05-22
6        7       Rohit   55000 2024-06-18
7        8        Neha   70000 2024-07-30
8        9        Amit   85000 2024-09-12
9       10       Rohit   65000 2024-11-08

In [13]:
# Q3: How many days between first and last sale?
print(df["sale_date"].max() - df["sale_date"].min())

298 days 00:00:00

In [14]:
# Q4: Filter to sales after May 1, 2024 (notice you can use string here — pandas converts it)
print(df[df["sale_date"] > "2024-05-01"])

   sale_id salesperson  amount  sale_date
5        6        Neha   90000 2024-05-22
6        7       Rohit   55000 2024-06-18
7        8        Neha   70000 2024-07-30
8        9        Amit   85000 2024-09-12
9       10       Rohit   65000 2024-11-08

In [15]:
# Q5: Try converting a bad date safely
bad_data = pd.Series(["2024-01-15", "garbage", "2024-03-10"])
print(pd.to_datetime(bad_data, errors="coerce"))

0   2024-01-15
1          NaT
2   2024-03-10
dtype: datetime64[ns]

In [16]:
df["year"] = df["sale_date"].dt.year
print(df[["sale_date", "year"]])

   sale_date  year
0 2024-01-15  2024
1 2024-02-20  2024
2 2024-02-25  2024
3 2024-03-10  2024
4 2024-04-05  2024
5 2024-05-22  2024
6 2024-06-18  2024
7 2024-07-30  2024
8 2024-09-12  2024
9 2024-11-08  2024

In [17]:
# Month number (1-12)
df["month_num"] = df["sale_date"].dt.month

# Month name
df["month_name"] = df["sale_date"].dt.month_name()

# Day of month (1-31)
df["day"] = df["sale_date"].dt.day

# Day of week — name
df["weekday_name"] = df["sale_date"].dt.day_name()

# Day of week — number (Monday=0, Sunday=6)
df["weekday_num"] = df["sale_date"].dt.weekday

# Quarter (1-4)
df["quarter"] = df["sale_date"].dt.quarter

# Day of year (1-365)
df["day_of_year"] = df["sale_date"].dt.dayofyear

print(df[["sale_date", "year", "month_name", "weekday_name", "quarter"]])

   sale_date  year month_name weekday_name  quarter
0 2024-01-15  2024    January       Monday        1
1 2024-02-20  2024   February      Tuesday        1
2 2024-02-25  2024   February       Sunday        1
3 2024-03-10  2024      March       Sunday        1
4 2024-04-05  2024      April       Friday        2
5 2024-05-22  2024        May    Wednesday        2
6 2024-06-18  2024       June      Tuesday        2
7 2024-07-30  2024       July      Tuesday        3
8 2024-09-12  2024  September     Thursday        3
9 2024-11-08  2024   November       Friday        4

In [18]:
# Sales by month
df.groupby("month_name")["amount"].sum()

month_name
April         45000
February     135000
January       50000
July          70000
June          55000
March         80000
May           90000
November      65000
September     85000
Name: amount, dtype: int64

In [19]:
# Sales by quarter
df.groupby("quarter")["amount"].sum()

quarter
1    265000
2    190000
3    155000
4     65000
Name: amount, dtype: int64

In [20]:
# Sales by weekday — do weekends sell more?
df.groupby("weekday_name")["amount"].sum()

weekday_name
Friday       110000
Monday        50000
Sunday       140000
Thursday      85000
Tuesday      200000
Wednesday     90000
Name: amount, dtype: int64

In [21]:
# Sales by year (when you have multi-year data)
df.groupby("year")["amount"].sum()

year
2024    675000
Name: amount, dtype: int64

In [22]:
# ISO week number
df["sale_date"].dt.isocalendar().week

0     3
1     8
2     8
3    10
4    14
5    21
6    25
7    31
8    37
9    45
Name: week, dtype: UInt32

In [23]:
# Start of week (Monday)
df["sale_date"].dt.to_period("W").dt.start_time

0   2024-01-15
1   2024-02-19
2   2024-02-19
3   2024-03-04
4   2024-04-01
5   2024-05-20
6   2024-06-17
7   2024-07-29
8   2024-09-09
9   2024-11-04
Name: sale_date, dtype: datetime64[ns]

In [24]:
# Is the date a weekend?
df["is_weekend"] = df["sale_date"].dt.weekday >=5

In [25]:
weekend_sales = df[df["is_weekend"]]["amount"].sum()
weekday_sales = df[~df["is_weekend"]]["amount"].sum()

In [26]:
df["hour"] = df["sale_date"].dt.hour
df["minute"] = df["sale_date"].dt.minute

In [27]:
# Q1: Which month had the highest total sales?
df.groupby("month_name")["amount"].sum().sort_values(ascending=False)

month_name
February     135000
May           90000
September     85000
March         80000
July          70000
November      65000
June          55000
January       50000
April         45000
Name: amount, dtype: int64

In [28]:
# Q2: Which weekday sees the most sales activity (by count, not amount)?
df.groupby("weekday_name")["sale_date"].count().sort_values(ascending=False)

weekday_name
Tuesday      3
Friday       2
Sunday       2
Monday       1
Thursday     1
Wednesday    1
Name: sale_date, dtype: int64

In [29]:
# Q3: Total sales per quarter
df.groupby("quarter")["amount"].sum()

quarter
1    265000
2    190000
3    155000
4     65000
Name: amount, dtype: int64

In [30]:
# Q4: Average sale per quarter
df.groupby("quarter")["amount"].mean()

quarter
1    66250.000000
2    63333.333333
3    77500.000000
4    65000.000000
Name: amount, dtype: float64

In [31]:
# Q5: Find sales that happened on a Friday
df[df["weekday_name"] == "Friday"]

,sale_id,salesperson,amount,sale_date,year,month_num,month_name,day,weekday_name,weekday_num,quarter,day_of_year,is_weekend,hour,minute
4,5,Amit,45000,2024-04-05,2024,4,April,5,Friday,4,2,96,False,0,0
9,10,Rohit,65000,2024-11-08,2024,11,November,8,Friday,4,4,313,False,0,0

In [35]:
#df = df.drop(columns=["yeaar"])

In [36]:
print(df.columns)

Index(['sale_id', 'salesperson', 'amount', 'sale_date', 'year', 'month_num',
       'month_name', 'day', 'weekday_name', 'weekday_num', 'quarter',
       'day_of_year', 'is_weekend', 'hour', 'minute'],
      dtype='object')

In [37]:
# When was the most recent sale?
latest = df["sale_date"].max()
print(f"Latest sale: {latest}")

# How many days ago was each sale?
df["days_ago"] = (latest - df["sale_date"]).dt.days
print(df[["sale_date", "days_ago"]])

Latest sale: 2024-11-08 00:00:00
   sale_date  days_ago
0 2024-01-15       298
1 2024-02-20       262
2 2024-02-25       257
3 2024-03-10       243
4 2024-04-05       217
5 2024-05-22       170
6 2024-06-18       143
7 2024-07-30       101
8 2024-09-12        57
9 2024-11-08         0

In [39]:
# Reference date
today = pd.Timestamp("2024-12-31")

In [40]:
# Days since each sale
df["days_since_sale"] = (today - df["sale_date"]).dt.days

In [41]:
# Sales in the last 90 days
df[df["days_since_sale"] <= 90]

,sale_id,salesperson,amount,sale_date,year,month_num,month_name,day,weekday_name,weekday_num,quarter,day_of_year,is_weekend,hour,minute,days_ago,days_since_sale
9,10,Rohit,65000,2024-11-08,2024,11,November,8,Friday,4,4,313,False,0,0,0,53

In [42]:
# Sales older than 6 months
df[df["days_since_sale"] > 180]

,sale_id,salesperson,amount,sale_date,year,month_num,month_name,day,weekday_name,weekday_num,quarter,day_of_year,is_weekend,hour,minute,days_ago,days_since_sale
0,1,Rohit,50000,2024-01-15,2024,1,January,15,Monday,0,1,15,False,0,0,298,351
1,2,Amit,75000,2024-02-20,2024,2,February,20,Tuesday,1,1,51,False,0,0,262,315
2,3,Rohit,60000,2024-02-25,2024,2,February,25,Sunday,6,1,56,True,0,0,257,310
3,4,Neha,80000,2024-03-10,2024,3,March,10,Sunday,6,1,70,True,0,0,243,296
4,5,Amit,45000,2024-04-05,2024,4,April,5,Friday,4,2,96,False,0,0,217,270
5,6,Neha,90000,2024-05-22,2024,5,May,22,Wednesday,2,2,143,False,0,0,170,223
6,7,Rohit,55000,2024-06-18,2024,6,June,18,Tuesday,1,2,170,False,0,0,143,196

In [43]:
# Sales between two specific dates
df[(df["sale_date"] >= "2024-04-01") & (df["sale_date"] <= "2024-06-30")]

,sale_id,salesperson,amount,sale_date,year,month_num,month_name,day,weekday_name,weekday_num,quarter,day_of_year,is_weekend,hour,minute,days_ago,days_since_sale
4,5,Amit,45000,2024-04-05,2024,4,April,5,Friday,4,2,96,False,0,0,217,270
5,6,Neha,90000,2024-05-22,2024,5,May,22,Wednesday,2,2,143,False,0,0,170,223
6,7,Rohit,55000,2024-06-18,2024,6,June,18,Tuesday,1,2,170,False,0,0,143,196

In [44]:
# Add 30 days
df["warranty_end"] = df["sale_date"] + pd.Timedelta(days=30)

In [45]:
# Subtract 7 days
df["campaign_date"] = df["sale_date"] - pd.Timedelta(days=7)

In [46]:
# Add a calendar month (handles month-length differences correctly)
df["follow_up"] = df["sale_date"] + pd.DateOffset(months=1)

In [47]:
# Q1: How many days between each sale and the most recent sale?
df["days_since_sale"] = (df["sale_date"].max() - df["sale_date"]).dt.days
print(df[["sale_date", "days_since_sale"]])

   sale_date  days_since_sale
0 2024-01-15              298
1 2024-02-20              262
2 2024-02-25              257
3 2024-03-10              243
4 2024-04-05              217
5 2024-05-22              170
6 2024-06-18              143
7 2024-07-30              101
8 2024-09-12               57
9 2024-11-08                0

In [48]:
# Q2: Filter to sales in the second half of 2024 (July onwards)
df[df["sale_date"] >= "2024-07-01"]

,sale_id,salesperson,amount,sale_date,year,month_num,month_name,day,weekday_name,weekday_num,quarter,day_of_year,is_weekend,hour,minute,days_ago,days_since_sale,warranty_end,campaign_date,follow_up
7,8,Neha,70000,2024-07-30,2024,7,July,30,Tuesday,1,3,212,False,0,0,101,101,2024-08-29,2024-07-23,2024-08-30
8,9,Amit,85000,2024-09-12,2024,9,September,12,Thursday,3,3,256,False,0,0,57,57,2024-10-12,2024-09-05,2024-10-12
9,10,Rohit,65000,2024-11-08,2024,11,November,8,Friday,4,4,313,False,0,0,0,0,2024-12-08,2024-11-01,2024-12-08

In [49]:
# Q3: For each salesperson, what's the date range of their sales?
df.groupby("salesperson")["sale_date"].agg(["min", "max"])

                   min        max
salesperson
Amit        2024-02-20 2024-09-12
Neha        2024-03-10 2024-07-30
Rohit       2024-01-15 2024-11-08

In [50]:
# Q4: For each salesperson, how many days from first to last sale?
span = df.groupby("salesperson")["sale_date"].agg(["min", "max"])
span["span_days"] = (span["max"] - span["min"]).dt.days
print(span)

                   min        max  span_days
salesperson
Amit        2024-02-20 2024-09-12        205
Neha        2024-03-10 2024-07-30        142
Rohit       2024-01-15 2024-11-08        298

In [51]:
# Q5: Add a "next quarter check-in" column — 90 days after each sale
df["check_in_date"] = df["sale_date"] + pd.Timedelta(days=90)
print(df[["sale_date", "check_in_date"]])

   sale_date check_in_date
0 2024-01-15    2024-04-14
1 2024-02-20    2024-05-20
2 2024-02-25    2024-05-25
3 2024-03-10    2024-06-08
4 2024-04-05    2024-07-04
5 2024-05-22    2024-08-20
6 2024-06-18    2024-09-16
7 2024-07-30    2024-10-28
8 2024-09-12    2024-12-11
9 2024-11-08    2025-02-06

In [54]:
today = pd.Timestamp("2024-12-31")
six_months_ago = today - pd.DateOffset(months=6)

weekend_recent = df[
    (df["sale_date"] >= six_months_ago) &     # last 6 months
    (df["sale_date"].dt.weekday >= 5)         # weekends only (Sat=5, Sun=6)
]

print(weekend_recent["amount"].mean())
print(f"\nNumber of weekend sales in last 6 months: {len(weekend_recent)}")

nan

Number of weekend sales in last 6 months: 0

In [55]:
df["is_weekend"] = df["sale_date"].dt.weekday >= 5
last_6_months = df[df["sale_date"] >= six_months_ago]

last_6_months.groupby("is_weekend")["amount"].agg(["mean", "count", "sum"])

                    mean  count     sum
is_weekend
False       73333.333333      3  220000

In [57]:
df_ts = df.set_index("sale_date")
print(df_ts.head())

            sale_id salesperson  amount  year  month_num month_name  day  \
sale_date
2024-01-15        1       Rohit   50000  2024          1    January   15
2024-02-20        2        Amit   75000  2024          2   February   20
2024-02-25        3       Rohit   60000  2024          2   February   25
2024-03-10        4        Neha   80000  2024          3      March   10
2024-04-05        5        Amit   45000  2024          4      April    5

           weekday_name  weekday_num  quarter  day_of_year  is_weekend  hour  \
sale_date
2024-01-15       Monday            0        1           15       False     0
2024-02-20      Tuesday            1        1           51       False     0
2024-02-25       Sunday            6        1           56        True     0
2024-03-10       Sunday            6        1           70        True     0
2024-04-05       Friday            4        2           96       False     0

            minute  days_ago  days_since_sale warranty_end campaign_date  \
sale_date
2024-01-15       0       298              298   2024-02-14    2024-01-08
2024-02-20       0       262              262   2024-03-21    2024-02-13
2024-02-25       0       257              257   2024-03-26    2024-02-18
2024-03-10       0       243              243   2024-04-09    2024-03-03
2024-04-05       0       217              217   2024-05-05    2024-03-29

            follow_up check_in_date
sale_date
2024-01-15 2024-02-15    2024-04-14
2024-02-20 2024-03-20    2024-05-20
2024-02-25 2024-03-25    2024-05-25
2024-03-10 2024-04-10    2024-06-08
2024-04-05 2024-05-05    2024-07-04

In [60]:
# Total sales per month
df_ts["amount"].resample("ME").sum()

sale_date
2024-01-31     50000
2024-02-29    135000
2024-03-31     80000
2024-04-30     45000
2024-05-31     90000
2024-06-30     55000
2024-07-31     70000
2024-08-31         0
2024-09-30     85000
2024-10-31         0
2024-11-30     65000
Freq: ME, Name: amount, dtype: int64

In [61]:
# Groupby month-name (what you did in Block 3)
df.groupby(df["sale_date"].dt.month_name())["amount"].sum()
# Shows 8 months — only the ones with sales

sale_date
April         45000
February     135000
January       50000
July          70000
June          55000
March         80000
May           90000
November      65000
September     85000
Name: amount, dtype: int64

In [63]:
# Resample monthly
df_ts["amount"].resample("ME").sum()
# Shows 11 months — INCLUDES Aug and Oct with 0

sale_date
2024-01-31     50000
2024-02-29    135000
2024-03-31     80000
2024-04-30     45000
2024-05-31     90000
2024-06-30     55000
2024-07-31     70000
2024-08-31         0
2024-09-30     85000
2024-10-31         0
2024-11-30     65000
Freq: ME, Name: amount, dtype: int64

In [64]:
df_ts["amount"].resample("ME").agg(["sum", "mean", "count"])

               sum     mean  count
sale_date
2024-01-31   50000  50000.0      1
2024-02-29  135000  67500.0      2
2024-03-31   80000  80000.0      1
2024-04-30   45000  45000.0      1
2024-05-31   90000  90000.0      1
2024-06-30   55000  55000.0      1
2024-07-31   70000  70000.0      1
2024-08-31       0      NaN      0
2024-09-30   85000  85000.0      1
2024-10-31       0      NaN      0
2024-11-30   65000  65000.0      1

In [66]:
df_ts["amount"].resample("QE").sum()

sale_date
2024-03-31    265000
2024-06-30    190000
2024-09-30    155000
2024-12-31     65000
Freq: QE-DEC, Name: amount, dtype: int64

In [67]:
# Q1: Monthly total sales (with missing months visible)
df_ts["amount"].resample("ME").sum()

sale_date
2024-01-31     50000
2024-02-29    135000
2024-03-31     80000
2024-04-30     45000
2024-05-31     90000
2024-06-30     55000
2024-07-31     70000
2024-08-31         0
2024-09-30     85000
2024-10-31         0
2024-11-30     65000
Freq: ME, Name: amount, dtype: int64

In [68]:
# Q2: Quarterly total sales
df_ts["amount"].resample("QE").sum()

sale_date
2024-03-31    265000
2024-06-30    190000
2024-09-30    155000
2024-12-31     65000
Freq: QE-DEC, Name: amount, dtype: int64

In [70]:
# Q3: Weekly sales count (how many sales each week?)
df_ts["amount"].resample("W").count()

sale_date
2024-01-21    1
2024-01-28    0
2024-02-04    0
2024-02-11    0
2024-02-18    0
2024-02-25    2
2024-03-03    0
2024-03-10    1
2024-03-17    0
2024-03-24    0
2024-03-31    0
2024-04-07    1
2024-04-14    0
2024-04-21    0
2024-04-28    0
2024-05-05    0
2024-05-12    0
2024-05-19    0
2024-05-26    1
2024-06-02    0
2024-06-09    0
2024-06-16    0
2024-06-23    1
2024-06-30    0
2024-07-07    0
2024-07-14    0
2024-07-21    0
2024-07-28    0
2024-08-04    1
2024-08-11    0
2024-08-18    0
2024-08-25    0
2024-09-01    0
2024-09-08    0
2024-09-15    1
2024-09-22    0
2024-09-29    0
2024-10-06    0
2024-10-13    0
2024-10-20    0
2024-10-27    0
2024-11-03    0
2024-11-10    1
Freq: W-SUN, Name: amount, dtype: int64

In [71]:
# Q4: Monthly stats — sum, mean, count
df_ts["amount"].resample("ME").agg(["sum", "mean", "count"])

               sum     mean  count
sale_date
2024-01-31   50000  50000.0      1
2024-02-29  135000  67500.0      2
2024-03-31   80000  80000.0      1
2024-04-30   45000  45000.0      1
2024-05-31   90000  90000.0      1
2024-06-30   55000  55000.0      1
2024-07-31   70000  70000.0      1
2024-08-31       0      NaN      0
2024-09-30   85000  85000.0      1
2024-10-31       0      NaN      0
2024-11-30   65000  65000.0      1

In [72]:
# Q5: Find your "best month" using resample
df_ts["amount"].resample("ME").sum().idxmax()

Timestamp('2024-02-29 00:00:00')