In [1]:
import pandas as pd

# Create the sales file
sales_csv = """sale_id,salesperson_id,amount,month
1,101,50000,Jan
2,102,75000,Jan
3,101,60000,Feb
4,103,80000,Feb
5,102,45000,Feb
6,103,90000,Mar
7,101,55000,Mar"""

with open("sales_v2.csv", "w") as f:
    f.write(sales_csv)

# Create the employees file
employees_csv = """salesperson_id,name,city,commission_rate
101,Rohit,Delhi,0.05
102,Amit,Mumbai,0.06
103,Neha,Bangalore,0.05
104,Vikram,Chennai,0.04"""

with open("employees.csv", "w") as f:
    f.write(employees_csv)

# Load both
sales_df = pd.read_csv("sales_v2.csv")
employees_df = pd.read_csv("employees.csv")

print("--- sales_df ---")
print(sales_df)
print("\n--- employees_df ---")
print(employees_df)

--- sales_df ---
   sale_id  salesperson_id  amount month
0        1             101   50000   Jan
1        2             102   75000   Jan
2        3             101   60000   Feb
3        4             103   80000   Feb
4        5             102   45000   Feb
5        6             103   90000   Mar
6        7             101   55000   Mar

--- employees_df ---
   salesperson_id    name       city  commission_rate
0             101   Rohit      Delhi             0.05
1             102    Amit     Mumbai             0.06
2             103    Neha  Bangalore             0.05
3             104  Vikram    Chennai             0.04

In [2]:
merged = pd.merge(sales_df, employees_df, on= "salesperson_id", how = "inner")
print(merged)

   sale_id  salesperson_id  amount month   name       city  commission_rate
0        1             101   50000   Jan  Rohit      Delhi             0.05
1        2             102   75000   Jan   Amit     Mumbai             0.06
2        3             101   60000   Feb  Rohit      Delhi             0.05
3        4             103   80000   Feb   Neha  Bangalore             0.05
4        5             102   45000   Feb   Amit     Mumbai             0.06
5        6             103   90000   Mar   Neha  Bangalore             0.05
6        7             101   55000   Mar  Rohit      Delhi             0.05

In [4]:
sales_df.merge(employees_df, on= "salesperson_id", how = "inner")

   sale_id  salesperson_id  amount month   name       city  commission_rate
0        1             101   50000   Jan  Rohit      Delhi             0.05
1        2             102   75000   Jan   Amit     Mumbai             0.06
2        3             101   60000   Feb  Rohit      Delhi             0.05
3        4             103   80000   Feb   Neha  Bangalore             0.05
4        5             102   45000   Feb   Amit     Mumbai             0.06
5        6             103   90000   Mar   Neha  Bangalore             0.05
6        7             101   55000   Mar  Rohit      Delhi             0.05

In [6]:
#If sales_df had a column called emp_id and employees_df had salesperson_id
#pd.merge(sales_df, employees_df, left_on="emp_id", right_on="salesperson_id", how="inner")

In [10]:
sales_df.merge(employees_df, on ="salesperson_id", how = "inner").groupby("city")["amount"].sum()

city
Bangalore    170000
Delhi        165000
Mumbai       120000
Name: amount, dtype: int64

In [11]:
# Q1: Inner join — how many rows in the result?
result = sales_df.merge(employees_df, on= "salesperson_id", how = "inner")
print(result)
print(f"\nShape: {result.shape}")

   sale_id  salesperson_id  amount month   name       city  commission_rate
0        1             101   50000   Jan  Rohit      Delhi             0.05
1        2             102   75000   Jan   Amit     Mumbai             0.06
2        3             101   60000   Feb  Rohit      Delhi             0.05
3        4             103   80000   Feb   Neha  Bangalore             0.05
4        5             102   45000   Feb   Amit     Mumbai             0.06
5        6             103   90000   Mar   Neha  Bangalore             0.05
6        7             101   55000   Mar  Rohit      Delhi             0.05

Shape: (7, 7)

In [12]:
# Q2: After joining, what's the total sales by city?
print(result.groupby("city")["amount"].sum())

city
Bangalore    170000
Delhi        165000
Mumbai       120000
Name: amount, dtype: int64

In [13]:
# Q3: What's the commission for each sale? 
# (multiply amount by commission_rate, store in a new column)
result["commission"] = result["amount"] * result["commission_rate"]
print(result[["name", "amount", "commission_rate", "commission"]])

    name  amount  commission_rate  commission
0  Rohit   50000             0.05      2500.0
1   Amit   75000             0.06      4500.0
2  Rohit   60000             0.05      3000.0
3   Neha   80000             0.05      4000.0
4   Amit   45000             0.06      2700.0
5   Neha   90000             0.05      4500.0
6  Rohit   55000             0.05      2750.0

In [14]:
# Q4: What's each salesperson's total commission?
print(result.groupby("name")["commission"].sum())

name
Amit     7200.0
Neha     8500.0
Rohit    8250.0
Name: commission, dtype: float64

In [15]:
sales_df.merge(employees_df, on="salesperson_id", how="left")

   sale_id  salesperson_id  amount month   name       city  commission_rate
0        1             101   50000   Jan  Rohit      Delhi             0.05
1        2             102   75000   Jan   Amit     Mumbai             0.06
2        3             101   60000   Feb  Rohit      Delhi             0.05
3        4             103   80000   Feb   Neha  Bangalore             0.05
4        5             102   45000   Feb   Amit     Mumbai             0.06
5        6             103   90000   Mar   Neha  Bangalore             0.05
6        7             101   55000   Mar  Rohit      Delhi             0.05

In [16]:
sales_df.merge(employees_df, on="salesperson_id", how="right")

   sale_id  salesperson_id   amount month    name       city  commission_rate
0      1.0             101  50000.0   Jan   Rohit      Delhi             0.05
1      3.0             101  60000.0   Feb   Rohit      Delhi             0.05
2      7.0             101  55000.0   Mar   Rohit      Delhi             0.05
3      2.0             102  75000.0   Jan    Amit     Mumbai             0.06
4      5.0             102  45000.0   Feb    Amit     Mumbai             0.06
5      4.0             103  80000.0   Feb    Neha  Bangalore             0.05
6      6.0             103  90000.0   Mar    Neha  Bangalore             0.05
7      NaN             104      NaN   NaN  Vikram    Chennai             0.04

In [17]:
sales_df.merge(employees_df, on="salesperson_id", how="outer")

   sale_id  salesperson_id   amount month    name       city  commission_rate
0      1.0             101  50000.0   Jan   Rohit      Delhi             0.05
1      3.0             101  60000.0   Feb   Rohit      Delhi             0.05
2      7.0             101  55000.0   Mar   Rohit      Delhi             0.05
3      2.0             102  75000.0   Jan    Amit     Mumbai             0.06
4      5.0             102  45000.0   Feb    Amit     Mumbai             0.06
5      4.0             103  80000.0   Feb    Neha  Bangalore             0.05
6      6.0             103  90000.0   Mar    Neha  Bangalore             0.05
7      NaN             104      NaN   NaN  Vikram    Chennai             0.04

In [20]:
# Q1: Left join — same as inner here?
left_result = sales_df.merge(employees_df, on = "salesperson_id", how = "left")
print(left_result.shape)
print(left_result)

(7, 7)
   sale_id  salesperson_id  amount month   name       city  commission_rate
0        1             101   50000   Jan  Rohit      Delhi             0.05
1        2             102   75000   Jan   Amit     Mumbai             0.06
2        3             101   60000   Feb  Rohit      Delhi             0.05
3        4             103   80000   Feb   Neha  Bangalore             0.05
4        5             102   45000   Feb   Amit     Mumbai             0.06
5        6             103   90000   Mar   Neha  Bangalore             0.05
6        7             101   55000   Mar  Rohit      Delhi             0.05

In [21]:
# Q2: Right join — how many rows?
right_result = sales_df.merge(employees_df, on="salesperson_id", how="right")
print(right_result.shape)
print(right_result)

(8, 7)
   sale_id  salesperson_id   amount month    name       city  commission_rate
0      1.0             101  50000.0   Jan   Rohit      Delhi             0.05
1      3.0             101  60000.0   Feb   Rohit      Delhi             0.05
2      7.0             101  55000.0   Mar   Rohit      Delhi             0.05
3      2.0             102  75000.0   Jan    Amit     Mumbai             0.06
4      5.0             102  45000.0   Feb    Amit     Mumbai             0.06
5      4.0             103  80000.0   Feb    Neha  Bangalore             0.05
6      6.0             103  90000.0   Mar    Neha  Bangalore             0.05
7      NaN             104      NaN   NaN  Vikram    Chennai             0.04

In [22]:
# Q3: Outer join — how many rows?
outer_result = sales_df.merge(employees_df, on="salesperson_id", how="outer")
print(outer_result.shape)
print(outer_result)

(8, 7)
   sale_id  salesperson_id   amount month    name       city  commission_rate
0      1.0             101  50000.0   Jan   Rohit      Delhi             0.05
1      3.0             101  60000.0   Feb   Rohit      Delhi             0.05
2      7.0             101  55000.0   Mar   Rohit      Delhi             0.05
3      2.0             102  75000.0   Jan    Amit     Mumbai             0.06
4      5.0             102  45000.0   Feb    Amit     Mumbai             0.06
5      4.0             103  80000.0   Feb    Neha  Bangalore             0.05
6      6.0             103  90000.0   Mar    Neha  Bangalore             0.05
7      NaN             104      NaN   NaN  Vikram    Chennai             0.04

In [23]:
# Q4: After right join, can we find employees with NO sales?
# Hint: filter for rows where sale_id is NaN
print(right_result[right_result["sale_id"].isna()])

   sale_id  salesperson_id  amount month    name     city  commission_rate
7      NaN             104     NaN   NaN  Vikram  Chennai             0.04

In [24]:
# Add product info to each sale
sales_with_products_csv = """sale_id,salesperson_id,product_id,amount,month
1,101,P01,50000,Jan
2,102,P02,75000,Jan
3,101,P03,60000,Feb
4,103,P01,80000,Feb
5,102,P02,45000,Feb
6,103,P03,90000,Mar
7,101,P01,55000,Mar"""

with open("sales_v3.csv", "w") as f:
    f.write(sales_with_products_csv)

# Create products lookup
products_csv = """product_id,product_name,category
P01,Laptop,Electronics
P02,Phone,Electronics
P03,Office Chair,Furniture"""

with open("products.csv", "w") as f:
    f.write(products_csv)

sales_df = pd.read_csv("sales_v3.csv")
products_df = pd.read_csv("products.csv")

print("--- sales_df ---")
print(sales_df)
print("\n--- products_df ---")
print(products_df)
print("\n--- employees_df (unchanged) ---")
print(employees_df)

--- sales_df ---
   sale_id  salesperson_id product_id  amount month
0        1             101        P01   50000   Jan
1        2             102        P02   75000   Jan
2        3             101        P03   60000   Feb
3        4             103        P01   80000   Feb
4        5             102        P02   45000   Feb
5        6             103        P03   90000   Mar
6        7             101        P01   55000   Mar

--- products_df ---
  product_id  product_name     category
0        P01        Laptop  Electronics
1        P02         Phone  Electronics
2        P03  Office Chair    Furniture

--- employees_df (unchanged) ---
   salesperson_id    name       city  commission_rate
0             101   Rohit      Delhi             0.05
1             102    Amit     Mumbai             0.06
2             103    Neha  Bangalore             0.05
3             104  Vikram    Chennai             0.04

In [25]:
full_view = sales_df.merge(employees_df, on="salesperson_id").merge(products_df, on="product_id")
print(full_view)

   sale_id  salesperson_id product_id  amount month   name       city  \
0        1             101        P01   50000   Jan  Rohit      Delhi
1        2             102        P02   75000   Jan   Amit     Mumbai
2        3             101        P03   60000   Feb  Rohit      Delhi
3        4             103        P01   80000   Feb   Neha  Bangalore
4        5             102        P02   45000   Feb   Amit     Mumbai
5        6             103        P03   90000   Mar   Neha  Bangalore
6        7             101        P01   55000   Mar  Rohit      Delhi

   commission_rate  product_name     category
0             0.05        Laptop  Electronics
1             0.06         Phone  Electronics
2             0.05  Office Chair    Furniture
3             0.05        Laptop  Electronics
4             0.06         Phone  Electronics
5             0.05  Office Chair    Furniture
6             0.05        Laptop  Electronics

In [42]:
# Q1: Sales by product category
full_view.groupby("category")["amount"].sum()

category
Electronics    305000
Furniture      150000
Name: amount, dtype: int64

In [41]:
# Q2: Sales by city + category (cross-tab)
full_view.groupby(["city", "category"])["amount"].sum()

city       category
Bangalore  Electronics     80000
           Furniture       90000
Delhi      Electronics    105000
           Furniture       60000
Mumbai     Electronics    120000
Name: amount, dtype: int64

In [40]:
# Q3: Top-selling product
full_view.groupby("product_name")["amount"].sum().idxmax()

'Laptop'

In [39]:
# Q4: Each salesperson's biggest deal — and what they sold
full_view.sort_values("amount", ascending=False).groupby("name").first()

,sale_id,salesperson_id,product_id,amount,month,city,commission_rate,product_name,category,commission
name,,,,,,,,,,
Amit,2,102,P02,75000,Jan,Mumbai,0.06,Phone,Electronics,4500.0
Neha,6,103,P03,90000,Mar,Bangalore,0.05,Office Chair,Furniture,4500.0
Rohit,3,101,P03,60000,Feb,Delhi,0.05,Office Chair,Furniture,3000.0

In [38]:
# Q1 — Total sales by category
full_view.groupby("category")["amount"].sum()

category
Electronics    305000
Furniture      150000
Name: amount, dtype: int64

In [37]:
# Q2 — Total sales by category AND city
full_view.groupby(["category", "city"])["amount"].sum()

category     city
Electronics  Bangalore     80000
             Delhi        105000
             Mumbai       120000
Furniture    Bangalore     90000
             Delhi         60000
Name: amount, dtype: int64

In [36]:
# Q3 — Which salesperson sold the most "Electronics"?
electronics = full_view[full_view["category"] == "Electronics"]
print(electronics.groupby("name")["amount"].sum().sort_values(ascending=False))

name
Amit     120000
Rohit    105000
Neha      80000
Name: amount, dtype: int64

In [34]:
# Q4 — Average sale amount per product
full_view.groupby("product_name")["amount"].mean()

product_name
Laptop          61666.666667
Office Chair    75000.000000
Phone           60000.000000
Name: amount, dtype: float64

In [35]:
# Q5 — Commission earned per product
full_view["commission"] = full_view["amount"] * full_view["commission_rate"]
full_view.groupby("product_name")["commission"].sum()

product_name
Laptop          9250.0
Office Chair    7500.0
Phone           7200.0
Name: commission, dtype: float64

In [45]:
electronics = full_view[full_view["category"] == "Electronics"]
print(electronics.groupby("name")["amount"].sum().sort_values(ascending=False))

name
Amit     120000
Rohit    105000
Neha      80000
Name: amount, dtype: int64