


Pandas is intresting can replace 60-70 lines of code into one line.
Nothing hard till now,
One thing I'm curious about for tomorrow
operations on dataset.

In [15]:
import pandas as pd
print(pd.__version__)

2.3.3

In [16]:
pd.Series(["Rohit", "Amit", "Neha"])

0    Rohit
1     Amit
2     Neha
dtype: object

In [17]:
pd.Series([25, 30, 28, 35])

0    25
1    30
2    28
3    35
dtype: int64

In [18]:
data = {
    "name": ["Rohit", "Amit", "Neha"],
    "age": [25, 30, 28],
    "city": ["Delhi", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)
print(df)

    name  age    city
0  Rohit   25   Delhi
1   Amit   30  Mumbai
2   Neha   28    Pune

In [19]:
data = {
    "name": ["Rohit", "Amit", "Neha"],
    "age": [25, 30, 28],
    "city": ["Delhi", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)
print(df)

    name  age    city
0  Rohit   25   Delhi
1   Amit   30  Mumbai
2   Neha   28    Pune

In [20]:
print(df["name"])
print(type(df["name"]))

0    Rohit
1     Amit
2     Neha
Name: name, dtype: object
<class 'pandas.core.series.Series'>

In [21]:
print(df[["name", "age"]])
print(type(df[["name", "age"]]))

    name  age
0  Rohit   25
1   Amit   30
2   Neha   28
<class 'pandas.core.frame.DataFrame'>

In [22]:
print(type(df[["name"]]))

<class 'pandas.core.frame.DataFrame'>

In [23]:
df = pd.read_csv("sales_data.csv")
print(df)

  salesperson  amount month
0       Rohit   50000   Jan
1        Amit   75000   Jan
2       Rohit   60000   Feb
3        Neha   80000   Feb
4        Amit   45000   Feb
5        Neha   90000   Mar
6       Rohit   55000   Mar

In [24]:
df.head()

  salesperson  amount month
0       Rohit   50000   Jan
1        Amit   75000   Jan
2       Rohit   60000   Feb
3        Neha   80000   Feb
4        Amit   45000   Feb

In [25]:
df.tail()

  salesperson  amount month
2       Rohit   60000   Feb
3        Neha   80000   Feb
4        Amit   45000   Feb
5        Neha   90000   Mar
6       Rohit   55000   Mar

In [26]:
df.shape

(7, 3)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   salesperson  7 non-null      object
 1   amount       7 non-null      int64
 2   month        7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

df.describe()

In [28]:
df.columns

Index(['salesperson', 'amount', 'month'], dtype='object')

In [29]:
df.dtypes

salesperson    object
amount          int64
month          object
dtype: object

In [30]:
print(df.describe())

             amount
count      7.000000
mean   65000.000000
std    16832.508231
min    45000.000000
25%    52500.000000
50%    60000.000000
75%    77500.000000
max    90000.000000

In [33]:
from IPython.display import display
display(df.describe())

             amount
count      7.000000
mean   65000.000000
std    16832.508231
min    45000.000000
25%    52500.000000
50%    60000.000000
75%    77500.000000
max    90000.000000