In [4]:
import pandas as pd
df = pd.read_csv("sales_data.csv")
print(df)

  salesperson  amount month
0       Rohit   50000   Jan
1        Amit   75000   Jan
2       Rohit   60000   Feb
3        Neha   80000   Feb
4        Amit   45000   Feb
5        Neha   90000   Mar
6       Rohit   55000   Mar

In [5]:
print(df.columns)
print(list(df.columns))

Index(['salesperson', 'amount', 'month'], dtype='object')
['salesperson', 'amount', 'month']

In [6]:
print("amount" in df.columns)
print("revenue" in df.columns)

True
False

In [7]:
print(df.amount)
print(df["amount"])

0    50000
1    75000
2    60000
3    80000
4    45000
5    90000
6    55000
Name: amount, dtype: int64
0    50000
1    75000
2    60000
3    80000
4    45000
5    90000
6    55000
Name: amount, dtype: int64

In [8]:
columns_i_need = ["salesperson", "amount"]
result = df[columns_i_need]
print(result)
print(type(result))

  salesperson  amount
0       Rohit   50000
1        Amit   75000
2       Rohit   60000
3        Neha   80000
4        Amit   45000
5        Neha   90000
6       Rohit   55000
<class 'pandas.core.frame.DataFrame'>

In [9]:
print("=== Original DataFrame ===")
print(df)

print("\n=== same data, but with custom index ===")
df_custom = df.copy()
df_custom.index = ["a", "b", "c", "d", "e", "f", "g"]
print(df_custom)

=== Original DataFrame ===
  salesperson  amount month
0       Rohit   50000   Jan
1        Amit   75000   Jan
2       Rohit   60000   Feb
3        Neha   80000   Feb
4        Amit   45000   Feb
5        Neha   90000   Mar
6       Rohit   55000   Mar

=== same data, but with custom index ===
  salesperson  amount month
a       Rohit   50000   Jan
b        Amit   75000   Jan
c       Rohit   60000   Feb
d        Neha   80000   Feb
e        Amit   45000   Feb
f        Neha   90000   Mar
g       Rohit   55000   Mar

In [10]:
print("--- original df.iloc[3] ---")
print(df.iloc[3])

print("\n--- original df.loc[3] ---")
print(df.loc[3])

--- original df.iloc[3] ---
salesperson     Neha
amount         80000
month            Feb
Name: 3, dtype: object

--- original df.loc[3] ---
salesperson     Neha
amount         80000
month            Feb
Name: 3, dtype: object

In [11]:
print("--- custom df_custom.iloc[3] ---")
print(df_custom.iloc[3])

print("\n--- custom df_custom.loc[3] ---")
print(df_custom.loc["d"])

--- custom df_custom.iloc[3] ---
salesperson     Neha
amount         80000
month            Feb
Name: d, dtype: object

--- custom df_custom.loc[3] ---
salesperson     Neha
amount         80000
month            Feb
Name: d, dtype: object

In [12]:
print(df.iloc[[0, 2, 4]])     
print(df.loc[[0, 2, 4]])

  salesperson  amount month
0       Rohit   50000   Jan
2       Rohit   60000   Feb
4        Amit   45000   Feb
  salesperson  amount month
0       Rohit   50000   Jan
2       Rohit   60000   Feb
4        Amit   45000   Feb

In [13]:
print(df.iloc[2, 1])
print(df.loc[2, "amount"])

60000
60000

In [14]:
print(df.loc[[0, 2, 4], ["salesperson", "amount"]])

  salesperson  amount
0       Rohit   50000
2       Rohit   60000
4        Amit   45000

In [15]:
print(df.iloc[1:4])
print(df.loc[1:4])

  salesperson  amount month
1        Amit   75000   Jan
2       Rohit   60000   Feb
3        Neha   80000   Feb
  salesperson  amount month
1        Amit   75000   Jan
2       Rohit   60000   Feb
3        Neha   80000   Feb
4        Amit   45000   Feb

In [16]:
print(df.iloc[0])

salesperson    Rohit
amount         50000
month            Jan
Name: 0, dtype: object

In [17]:
print(df.iloc[0:3])

  salesperson  amount month
0       Rohit   50000   Jan
1        Amit   75000   Jan
2       Rohit   60000   Feb

In [18]:
print(df.loc[0:3])

  salesperson  amount month
0       Rohit   50000   Jan
1        Amit   75000   Jan
2       Rohit   60000   Feb
3        Neha   80000   Feb

In [19]:
print(df.loc[2, "salesperson"])

Rohit

In [20]:
print(df.iloc[[1, 3], [0, 2]])

  salesperson month
1        Amit   Jan
3        Neha   Feb

In [21]:
mask = df["amount"] > 60000
print(mask)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
Name: amount, dtype: bool

In [22]:
big_sales = df[mask]
print(big_sales)

  salesperson  amount month
1        Amit   75000   Jan
3        Neha   80000   Feb
5        Neha   90000   Mar

In [23]:
big_sales = df[df["amount"] > 60000]
print(big_sales)

  salesperson  amount month
1        Amit   75000   Jan
3        Neha   80000   Feb
5        Neha   90000   Mar

In [24]:
df[df["salesperson"] == "Neha"]

  salesperson  amount month
3        Neha   80000   Feb
5        Neha   90000   Mar

In [25]:
df[df["month"].isin(["Jan", "Feb"])]

  salesperson  amount month
0       Rohit   50000   Jan
1        Amit   75000   Jan
2       Rohit   60000   Feb
3        Neha   80000   Feb
4        Amit   45000   Feb

In [26]:
df[df["salesperson"].str.startswith("R")]   
df[df["salesperson"].str.contains("e")]

  salesperson  amount month
3        Neha   80000   Feb
5        Neha   90000   Mar

In [28]:
df[df["amount"] > 50000]

  salesperson  amount month
1        Amit   75000   Jan
2       Rohit   60000   Feb
3        Neha   80000   Feb
5        Neha   90000   Mar
6       Rohit   55000   Mar

In [29]:
df[df["salesperson"] == "Rohit"]

  salesperson  amount month
0       Rohit   50000   Jan
2       Rohit   60000   Feb
6       Rohit   55000   Mar

In [32]:
df[df["month"] == "Mar"]

  salesperson  amount month
5        Neha   90000   Mar
6       Rohit   55000   Mar

In [33]:
df[df["salesperson"].str.contains("a")]

  salesperson  amount month
3        Neha   80000   Feb
5        Neha   90000   Mar

In [34]:
df[df["month"].isin(["Jan", "Mar"])]

  salesperson  amount month
0       Rohit   50000   Jan
1        Amit   75000   Jan
5        Neha   90000   Mar
6       Rohit   55000   Mar

In [36]:
# Rohit's big sales (Rohit AND amount > 50000)
df[(df["salesperson"] == "Rohit") & (df["amount"] > 50000)]

  salesperson  amount month
2       Rohit   60000   Feb
6       Rohit   55000   Mar

In [37]:
# January or February sales
df[(df["month"] == "Jan") | (df["month"] == "Feb")]

  salesperson  amount month
0       Rohit   50000   Jan
1        Amit   75000   Jan
2       Rohit   60000   Feb
3        Neha   80000   Feb
4        Amit   45000   Feb

In [38]:
# Same thing, cleaner with .isin()
df[df["month"].isin(["Jan", "Feb"])]

  salesperson  amount month
0       Rohit   50000   Jan
1        Amit   75000   Jan
2       Rohit   60000   Feb
3        Neha   80000   Feb
4        Amit   45000   Feb

In [39]:
# Sales NOT in March
df[~(df["month"] == "Mar")]

  salesperson  amount month
0       Rohit   50000   Jan
1        Amit   75000   Jan
2       Rohit   60000   Feb
3        Neha   80000   Feb
4        Amit   45000   Feb

In [40]:
# Equivalent to above, slightly cleaner
df[df["month"] != "Mar"]

  salesperson  amount month
0       Rohit   50000   Jan
1        Amit   75000   Jan
2       Rohit   60000   Feb
3        Neha   80000   Feb
4        Amit   45000   Feb

In [41]:
df["amount"] > 50000 & df["salesperson"] == "Rohit"
# Python tries to do: 50000 & df["salesperson"]  ← nonsense

TypeError: Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]

In [42]:
df[
    (df["salesperson"] == "Rohit") & 
    (df["month"] == "Jan") & 
    (df["amount"] > 40000)
]

  salesperson  amount month
0       Rohit   50000   Jan

In [43]:
# Q1: Rohit's sales above 50000
df[(df["salesperson"] == "Rohit") & (df["amount"] > 50000)]

  salesperson  amount month
2       Rohit   60000   Feb
6       Rohit   55000   Mar

In [44]:
# Q2: Sales NOT by Neha
df[df["salesperson"] != "Neha"]

  salesperson  amount month
0       Rohit   50000   Jan
1        Amit   75000   Jan
2       Rohit   60000   Feb
4        Amit   45000   Feb
6       Rohit   55000   Mar

In [45]:
# Q3: Big sales (>60000) in Feb or Mar
df[(df["amount"] > 60000) & (df["month"].isin(["Feb", "Mar"]))]

  salesperson  amount month
3        Neha   80000   Feb
5        Neha   90000   Mar

In [46]:
# Q4: All sales by Amit OR Neha
df[df["salesperson"].isin(["Amit", "Neha"])]

  salesperson  amount month
1        Amit   75000   Jan
3        Neha   80000   Feb
4        Amit   45000   Feb
5        Neha   90000   Mar

In [47]:
# Q5: Small sales (<50000) NOT in January
df[(df["amount"] < 50000) & (df["month"] != "Jan")]

  salesperson  amount month
4        Amit   45000   Feb