in pandas method are important
Knowing methods as much as possible is the key
syntax is short and precise i have to take care of it

In [2]:
import pandas as pd

df = pd.read_csv("sales_data.csv")
print(df)

  salesperson  amount month
0       Rohit   50000   Jan
1        Amit   75000   Jan
2       Rohit   60000   Feb
3        Neha   80000   Feb
4        Amit   45000   Feb
5        Neha   90000   Mar
6       Rohit   55000   Mar

In [4]:
df.sort_values(by = "amount")

  salesperson  amount month
4        Amit   45000   Feb
0       Rohit   50000   Jan
6       Rohit   55000   Mar
2       Rohit   60000   Feb
1        Amit   75000   Jan
3        Neha   80000   Feb
5        Neha   90000   Mar

In [5]:
df.sort_values(by="amount", ascending=False)

  salesperson  amount month
5        Neha   90000   Mar
3        Neha   80000   Feb
1        Amit   75000   Jan
2       Rohit   60000   Feb
6       Rohit   55000   Mar
0       Rohit   50000   Jan
4        Amit   45000   Feb

In [6]:
df.sort_values(by=["month", "amount"], ascending=[True, False])

  salesperson  amount month
3        Neha   80000   Feb
2       Rohit   60000   Feb
4        Amit   45000   Feb
1        Amit   75000   Jan
0       Rohit   50000   Jan
5        Neha   90000   Mar
6       Rohit   55000   Mar

In [8]:
df.sort_index()

  salesperson  amount month
0       Rohit   50000   Jan
1        Amit   75000   Jan
2       Rohit   60000   Feb
3        Neha   80000   Feb
4        Amit   45000   Feb
5        Neha   90000   Mar
6       Rohit   55000   Mar

In [9]:
df.sort_index(ascending=False)

  salesperson  amount month
6       Rohit   55000   Mar
5        Neha   90000   Mar
4        Amit   45000   Feb
3        Neha   80000   Feb
2       Rohit   60000   Feb
1        Amit   75000   Jan
0       Rohit   50000   Jan

In [12]:
# Returns a new DataFrame (original unchanged)
sorted_df = df.sort_values(by="amount", ascending=False)
print(sorted_df)

  salesperson  amount month
5        Neha   90000   Mar
3        Neha   80000   Feb
1        Amit   75000   Jan
2       Rohit   60000   Feb
6       Rohit   55000   Mar
0       Rohit   50000   Jan
4        Amit   45000   Feb

In [14]:
# Modifies original (returns None)
df.sort_values(by="amount", ascending=False, inplace=True)

In [15]:
df_sorted = df.sort_values(by="amount", ascending=False)

In [16]:
# Q1: Sort by salesperson alphabetically
df.sort_values(by="salesperson")

  salesperson  amount month
1        Amit   75000   Jan
4        Amit   45000   Feb
5        Neha   90000   Mar
3        Neha   80000   Feb
2       Rohit   60000   Feb
6       Rohit   55000   Mar
0       Rohit   50000   Jan

In [17]:
# Q2: Top 3 highest sales — combine sort with .head()
df.sort_values(by="amount", ascending=False).head(3)

  salesperson  amount month
5        Neha   90000   Mar
3        Neha   80000   Feb
1        Amit   75000   Jan

In [18]:
# Q3: Sort by month ascending, then amount descending
df.sort_values(by=["month", "amount"], ascending=[True, False])

  salesperson  amount month
3        Neha   80000   Feb
2       Rohit   60000   Feb
4        Amit   45000   Feb
1        Amit   75000   Jan
0       Rohit   50000   Jan
5        Neha   90000   Mar
6       Rohit   55000   Mar

In [19]:
df["amount"].sum()      # 455000 — total

np.int64(455000)

In [20]:
df["amount"].mean()     # 65000 — average

np.float64(65000.0)

In [21]:
df["amount"].max()      # 90000 — largest

np.int64(90000)

In [22]:
df["amount"].min()      # 45000 — smallest

np.int64(45000)

In [23]:
df["amount"].count()    # 7 — number of non-null values

np.int64(7)

In [24]:
df["amount"].median()   # middle value when sorted

np.float64(60000.0)

In [25]:
df["amount"].std()      # standard deviation (spread)

np.float64(16832.508230603464)

In [26]:
df["amount"].sum()      # total

np.int64(455000)

In [27]:
df["amount"].nunique()  # number of unique values

7

In [28]:
df["amount"].quantile(0.25)   # 25th percentile (Q1)

np.float64(52500.0)

In [29]:
df["amount"].quantile(0.75)   # 75th percentile (Q3)

np.float64(77500.0)

In [30]:
# Q1: What's the total sales across all rows?
df["amount"].sum()

np.int64(455000)

In [31]:

# Q2: What's the average sale amount?
df["amount"].mean()

np.float64(65000.0)

In [32]:
# Q3: What's the biggest single sale?
df["amount"].max()

np.int64(90000)

In [33]:
# Q4: How many sales records exist?
df["amount"].count()
# vs.

7

In [35]:
len(df)
# Are they the same? When would they differ?

7

In [36]:

# Q5: What's the standard deviation?
df["amount"].std()
# How would you interpret this number compared to the mean?

np.float64(16832.508230603464)

In [37]:
df["salesperson"].unique()
# array(['Rohit', 'Amit', 'Neha'], dtype=object)

array(['Neha', 'Amit', 'Rohit'], dtype=object)

In [38]:

df["month"].unique()
# array(['Jan', 'Feb', 'Mar'], dtype=object)

array(['Mar', 'Feb', 'Jan'], dtype=object)

In [39]:
df["salesperson"].nunique()    # 3 (three different people)

3

In [40]:
df["month"].nunique()          # 3 (three different months)

3

In [41]:
df["salesperson"].value_counts()

salesperson
Rohit    3
Neha     2
Amit     2
Name: count, dtype: int64

In [42]:
# Sort by index instead of frequency
df["month"].value_counts().sort_index()

month
Feb    3
Jan    2
Mar    2
Name: count, dtype: int64

In [43]:
# Return percentages instead of counts
df["salesperson"].value_counts(normalize=True)
# Rohit    0.428571
# Neha     0.285714
# Amit     0.285714

salesperson
Rohit    0.428571
Neha     0.285714
Amit     0.285714
Name: proportion, dtype: float64

In [44]:
# Include NaN counts
df["salesperson"].value_counts(dropna=False)

salesperson
Rohit    3
Neha     2
Amit     2
Name: count, dtype: int64

In [45]:
# Q1: How many unique salespeople?
df["salesperson"].nunique()

3

In [46]:
# Q2: List all unique months
df["month"].unique()

array(['Mar', 'Feb', 'Jan'], dtype=object)

In [47]:

# Q3: How many sales did each salesperson make?
df["salesperson"].value_counts()

salesperson
Rohit    3
Neha     2
Amit     2
Name: count, dtype: int64

In [48]:
# Q4: What percentage of total sales records belong to each month?
df["month"].value_counts(normalize=True)

month
Feb    0.428571
Mar    0.285714
Jan    0.285714
Name: proportion, dtype: float64

In [49]:

# Q5: Which salesperson had the most transactions?
df["salesperson"].value_counts().head(1)

salesperson
Rohit    3
Name: count, dtype: int64

In [50]:
# or:
df["salesperson"].value_counts().idxmax()    # returns just the name

'Rohit'

In [51]:
df[df["salesperson"] == "Rohit"]["amount"].sum()

np.int64(165000)

In [55]:
df[df["month"] == "Feb"]["amount"].mean()

np.float64(61666.666666666664)

In [54]:
df[df["month"] == "Feb"]["amount"].mean()

np.float64(61666.666666666664)

In [56]:
df[df["salesperson"] == "Rohit"].sort_values(by= "amount",  ascending = False).head(3)

  salesperson  amount month
2       Rohit   60000   Feb
6       Rohit   55000   Mar
0       Rohit   50000   Jan

In [59]:
df[df["amount"] > 60000]["salesperson"].value_counts()

salesperson
Neha    2
Amit    1
Name: count, dtype: int64

In [60]:
# Q1: Total sales in March
df[df["month"] == "Mar"]["amount"].sum()

np.int64(145000)

In [61]:
# Q2: How many sales did Neha make?
df[df["salesperson"] == "Neha"]["salesperson"].count()
# or:

np.int64(2)

In [62]:
len(df[df["salesperson"] == "Neha"])

2

In [63]:
# Q3: Average sale for Amit
df[df["salesperson"] == "Amit"]["amount"].mean()

np.float64(60000.0)

In [64]:
# Q4: Biggest single sale in Feb
df[df["month"] == "Feb"]["amount"].max()

np.int64(80000)

In [65]:
# Q5: Total sales by Rohit AND Neha combined
df[df["salesperson"].isin(["Rohit", "Neha"])]["amount"].sum()

np.int64(335000)

In [66]:
def quick_report(df):
    print(f"Total Sales: ₹{df['amount'].sum():,}")
    print(f"Number of Transactions: {df['amount'].count()}")
    print(f"Average Sale: ₹{df['amount'].mean():,.0f}")
    print(f"\n--- Sales by Person ---")
    print(df.groupby("salesperson")["amount"].sum().sort_values(ascending=False))
    print(f"\n--- Sales by Month ---")
    print(df.groupby("month")["amount"].sum().sort_values(ascending=False))
    print(f"\n--- Top Performer ---")
    top = df.groupby("salesperson")["amount"].sum().idxmax()
    print(f"{top} with ₹{df[df['salesperson']==top]['amount'].sum():,}")

quick_report(df)

Total Sales: ₹455,000
Number of Transactions: 7
Average Sale: ₹65,000

--- Sales by Person ---
salesperson
Neha     170000
Rohit    165000
Amit     120000
Name: amount, dtype: int64

--- Sales by Month ---
month
Feb    185000
Mar    145000
Jan    125000
Name: amount, dtype: int64

--- Top Performer ---
Neha with ₹170,000