In [1]:
import pandas as pd

df = pd.read_csv("sales_data.csv")
print(df)

  salesperson  amount month
0       Rohit   50000   Jan
1        Amit   75000   Jan
2       Rohit   60000   Feb
3        Neha   80000   Feb
4        Amit   45000   Feb
5        Neha   90000   Mar
6       Rohit   55000   Mar

In [2]:
df.groupby("salesperson")["amount"].sum()

salesperson
Amit     120000
Neha     170000
Rohit    165000
Name: amount, dtype: int64

In [3]:
grouped = df.groupby("salesperson")
print(grouped.groups)

{'Amit': [1, 4], 'Neha': [3, 5], 'Rohit': [0, 2, 6]}

In [4]:
grouped = df.groupby("salesperson")
print(grouped.get_group("Rohit"))

  salesperson  amount month
0       Rohit   50000   Jan
2       Rohit   60000   Feb
6       Rohit   55000   Mar

In [5]:
# Q1: See how pandas tracks groups
grouped = df.groupby("month")
print(grouped.groups)

# Q2: Get just February's data
print(grouped.get_group("Feb"))

# Q3: How many groups exist?
print(len(grouped))

# Q4: Iterate over groups (rare but useful for debugging)
for name, group in df.groupby("salesperson"):
    print(f"--- {name} ---")
    print(group)
    print()

{'Feb': [2, 3, 4], 'Jan': [0, 1], 'Mar': [5, 6]}
  salesperson  amount month
2       Rohit   60000   Feb
3        Neha   80000   Feb
4        Amit   45000   Feb
3
--- Amit ---
  salesperson  amount month
1        Amit   75000   Jan
4        Amit   45000   Feb

--- Neha ---
  salesperson  amount month
3        Neha   80000   Feb
5        Neha   90000   Mar

--- Rohit ---
  salesperson  amount month
0       Rohit   50000   Jan
2       Rohit   60000   Feb
6       Rohit   55000   Mar

In [6]:
# Sales per salesperson (your old get_sales_by_person)
df.groupby("salesperson")["amount"].sum()

salesperson
Amit     120000
Neha     170000
Rohit    165000
Name: amount, dtype: int64

In [7]:
# Sales per month (your old get_sales_by_month)
df.groupby("month")["amount"].sum()

month
Feb    185000
Jan    125000
Mar    145000
Name: amount, dtype: int64

In [8]:
# Number of sales per salesperson
df.groupby("salesperson")["amount"].count()

salesperson
Amit     2
Neha     2
Rohit    3
Name: amount, dtype: int64

In [9]:
# Average sale per salesperson
df.groupby("salesperson")["amount"].mean()

salesperson
Amit     60000.0
Neha     85000.0
Rohit    55000.0
Name: amount, dtype: float64

In [10]:
# Biggest sale by each salesperson
df.groupby("salesperson")["amount"].max()

salesperson
Amit     75000
Neha     90000
Rohit    60000
Name: amount, dtype: int64

In [11]:
# Smallest sale by each salesperson
df.groupby("salesperson")["amount"].min()

salesperson
Amit     45000
Neha     80000
Rohit    50000
Name: amount, dtype: int64

In [12]:
# Variety: standard deviation per salesperson
df.groupby("salesperson")["amount"].std()

salesperson
Amit     21213.203436
Neha      7071.067812
Rohit     5000.000000
Name: amount, dtype: float64

In [13]:
result = df.groupby("salesperson")["amount"].sum()
print(type(result))    # <class 'pandas.core.series.Series'>
print(result.index)    # Index(['Amit', 'Neha', 'Rohit'], dtype='object', name='salesperson')
print(result.values)   # array([120000, 170000, 165000])

<class 'pandas.core.series.Series'>
Index(['Amit', 'Neha', 'Rohit'], dtype='object', name='salesperson')
[120000 170000 165000]

In [14]:
# Top performer first
df.groupby("salesperson")["amount"].sum().sort_values(ascending=False)

# Output:
# salesperson
# Neha     170000
# Rohit    165000
# Amit     120000

salesperson
Neha     170000
Rohit    165000
Amit     120000
Name: amount, dtype: int64

In [15]:
df.groupby("salesperson")["amount"].sum().idxmax()
# 'Neha'

'Neha'

In [16]:
# Q1: Total amount per month, sorted highest first
df.groupby("salesperson")["amount"].sum().sort_values(ascending = False)

salesperson
Neha     170000
Rohit    165000
Amit     120000
Name: amount, dtype: int64

In [17]:
# Q2: Average sale per month
df.groupby("month")["amount"].mean()

month
Feb    61666.666667
Jan    62500.000000
Mar    72500.000000
Name: amount, dtype: float64

In [18]:
# Q3: How many transactions per salesperson?
df.groupby("salesperson")["amount"].count()

salesperson
Amit     2
Neha     2
Rohit    3
Name: amount, dtype: int64

In [20]:

# Q4: Which month had the highest total sales?
df.groupby("month")["amount"].sum().idxmax()

'Feb'

In [21]:
# Q5: Range (max - min) per salesperson
df.groupby("salesperson")["amount"].max() - df.groupby("salesperson")["amount"].min()

salesperson
Amit     30000
Neha     10000
Rohit    10000
Name: amount, dtype: int64

In [23]:
df.groupby("salesperson")["amount"].agg(["sum", "mean", "count"])

                sum     mean  count
salesperson
Amit         120000  60000.0      2
Neha         170000  85000.0      2
Rohit        165000  55000.0      3

In [24]:
df.groupby("salesperson")["amount"].agg(
    total = "sum",
    average= "mean", 
    transections = "count"
)

              total  average  transections
salesperson
Amit         120000  60000.0             2
Neha         170000  85000.0             2
Rohit        165000  55000.0             3

In [25]:
df.groupby("salesperson").agg(
    total_amount=("amount", "sum"),
    avg_amount=("amount", "mean"),
    num_sales=("amount", "count")
)

             total_amount  avg_amount  num_sales
salesperson
Amit               120000     60000.0          2
Neha               170000     85000.0          2
Rohit              165000     55000.0          3

In [27]:
# Q1: For each month, show sum, mean, and count of sales
df.groupby("month")["amount"].agg(["sum", "mean", "count"])

          sum          mean  count
month
Feb    185000  61666.666667      3
Jan    125000  62500.000000      2
Mar    145000  72500.000000      2

In [28]:
# Q2: For each salesperson, show their stats with custom names
df.groupby("salesperson")["amount"].agg(
    total="sum",
    average="mean",
    biggest="max",
    smallest="min"
)

              total  average  biggest  smallest
salesperson
Amit         120000  60000.0    75000     45000
Neha         170000  85000.0    90000     80000
Rohit        165000  55000.0    60000     50000

In [29]:
# Q3: Which salesperson has the highest average?
df.groupby("salesperson")["amount"].mean().idxmax()

'Neha'

In [30]:
df.groupby(["month", "salesperson"])["amount"].sum()

month  salesperson
Feb    Amit           45000
       Neha           80000
       Rohit          60000
Jan    Amit           75000
       Rohit          50000
Mar    Neha           90000
       Rohit          55000
Name: amount, dtype: int64

In [31]:
df.groupby(["month", "salesperson"])["amount"].sum().reset_index()

  month salesperson  amount
0   Feb        Amit   45000
1   Feb        Neha   80000
2   Feb       Rohit   60000
3   Jan        Amit   75000
4   Jan       Rohit   50000
5   Mar        Neha   90000
6   Mar       Rohit   55000

In [32]:
# Q1: Total sales by month and salesperson
df.groupby(["month", "salesperson"])["amount"].sum()

month  salesperson
Feb    Amit           45000
       Neha           80000
       Rohit          60000
Jan    Amit           75000
       Rohit          50000
Mar    Neha           90000
       Rohit          55000
Name: amount, dtype: int64

In [33]:
# Q2: Same thing but as a regular DataFrame
df.groupby(["month", "salesperson"])["amount"].sum().reset_index()

  month salesperson  amount
0   Feb        Amit   45000
1   Feb        Neha   80000
2   Feb       Rohit   60000
3   Jan        Amit   75000
4   Jan       Rohit   50000
5   Mar        Neha   90000
6   Mar       Rohit   55000

In [34]:
# Q3: Average sale by month and salesperson
df.groupby(["month", "salesperson"])["amount"].mean()

month  salesperson
Feb    Amit           45000.0
       Neha           80000.0
       Rohit          60000.0
Jan    Amit           75000.0
       Rohit          50000.0
Mar    Neha           90000.0
       Rohit          55000.0
Name: amount, dtype: float64

In [35]:

# Q4: Multiple stats by month and salesperson
df.groupby(["month", "salesperson"])["amount"].agg(["sum", "mean", "count"])

                     sum     mean  count
month salesperson
Feb   Amit         45000  45000.0      1
      Neha         80000  80000.0      1
      Rohit        60000  60000.0      1
Jan   Amit         75000  75000.0      1
      Rohit        50000  50000.0      1
Mar   Neha         90000  90000.0      1
      Rohit        55000  55000.0      1

In [43]:
df.groupby(["month", "salesperson"])["amount"].agg(["sum", "mean", "count"]).reset_index()

  month salesperson    sum     mean  count
0   Feb        Amit  45000  45000.0      1
1   Feb        Neha  80000  80000.0      1
2   Feb       Rohit  60000  60000.0      1
3   Jan        Amit  75000  75000.0      1
4   Jan       Rohit  50000  50000.0      1
5   Mar        Neha  90000  90000.0      1
6   Mar       Rohit  55000  55000.0      1

In [45]:
def quick_report(df):
    print(f"Total Sales: ₹{df['amount'].sum():,}")
    print(f"Number of Transactions: {len(df)}")
    print(f"Average Sale Value: ₹{df['amount'].mean():,.0f}")
    
    print(f"\n--- Sales by Person (sorted) ---")
    print(df.groupby("salesperson")["amount"].sum().sort_values(ascending=False))
    
    print(f"\n--- Sales by Month (sorted) ---")
    print(df.groupby("month")["amount"].sum().sort_values(ascending=False))
    
    print(f"\n--- Top Performer ---")
    top_name = df.groupby("salesperson")["amount"].sum().idxmax()
    top_amount = df.groupby("salesperson")["amount"].sum().max()
    print(f"{top_name} with ₹{top_amount:,}")
    
    print(f"\n--- Big Sales (>₹60,000) ---")
    big_sellers = df[df["amount"] > 60000]["salesperson"].unique()
    print(", ".join(big_sellers))

    
    print(f"\n--- Sales Percentiles ---")
    print(f"25th: ₹{df['amount'].quantile(0.25):,.0f}")
    print(f"50th (median): ₹{df['amount'].quantile(0.50):,.0f}")
    print(f"75th: ₹{df['amount'].quantile(0.75):,.0f}")

quick_report(df)

Total Sales: ₹455,000
Number of Transactions: 7
Average Sale Value: ₹65,000

--- Sales by Person (sorted) ---
salesperson
Neha     170000
Rohit    165000
Amit     120000
Name: amount, dtype: int64

--- Sales by Month (sorted) ---
month
Feb    185000
Mar    145000
Jan    125000
Name: amount, dtype: int64

--- Top Performer ---
Neha with ₹170,000

--- Big Sales (>₹60,000) ---
Amit, Neha

--- Sales Percentiles ---
25th: ₹52,500
50th (median): ₹60,000
75th: ₹77,500